### ISSUE TITLE
create/fix contact page

### ISSUE THREAD

**Issue by srondal** [WAJUG/wajug.github.com#3]

**Comment by omlip** [comment]
@srondal a-t-on une KEY API pour utiliser google maps ?

**Comment by omlip** [comment]
as discussed with Stephane, it should not be a good idea to put a google map since we do not have one place, so I will fix the page and put a screenshot for approval

**Comment by omlip** [comment]
soms mail provider to use with Jekyll
heroku, mailgun, mandrill, mailjet

useful page
https://tuananh.org/2015/01/20/how-to-create-a-contact-form-with-jekyll/

**Comment by srondal** [comment]
Yes, please remove the map
For the mail provider, we already have a mailgun account for Arexo
Will give you the credentials

That being said, we could also use a forms provider and style it to Tehran wajug style

We used jotforms quite successfully for d4k registrations
